[package]
name = "qweekertom/gamestatetyped"
description = "Data handler and replication derived off the work of Leifstout"
version = "1.0.0"
license = "MIT"
authors = ["Qweekertom <qweekertom@gmail.com>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml", "LICENSE"]

[dependencies]
Networker = "leifstout/networker@0.3.1"
